apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubetrack.fullname" $ }}
  labels:
    {{- include "kubetrack.labels" $ | nindent 4 }}
data:
  config.yaml: |
    apiVersion: kubetrack.io/v1
    kind: KubeTrackConfiguration
    {{- toYaml .Values.kubetrack.config | nindent 4 }}
