apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubetrack.fullname" $ }}
  labels:
    {{- include "kubetrack.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubetrack.fullname" $ }}
  labels:
    {{- include "kubetrack.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubetrack.fullname" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubetrack.fullname" $ }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "kubetrack.fullname" $ }}
